### ISSUE TITLE
Solution to added in Java

### ISSUE THREAD

**Issue by SanjeevKumar22** [smv1999/CompetitiveProgrammingQuestionBank#198]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
solutions to some in java

**Describe the solution you'd like**

**Additional context**

**Comment by smv1999** [comment]
Sure @SanjeevKumar22  , you may go ahead! But I am afraid this won't be considered towards your contribution to DevIncept 30 days of contribution as the official date for the same is 01 July.

Otherwise,  Utilise the time till 30th June in going through the repo and existing problems and the ways in which they can be optimised or improved. Also, make a list of problems/solutions that you would like to add and keep them ready. Once I receive any official information from the DevIncept team, I would let you know in the slack channel.

**Comment by smv1999** [comment]
Please give a detailed description of this issue. For which problems are you willing to provide solutions in Java ?
